[package]
name = "simavr-sim"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
simavr-sys = "1.5"
tempfile = "3.1"
vsprintf = "2.0"
